### ISSUE TITLE
Support HTTP protocol

### ISSUE THREAD

**Issue by KMax** [Enteee/git-sync-mirror#1]
I have a repo which for some reason doesn't use HTTPS. As I see in the logs, there is a regex which assumes HTTPS by default:

```
sed -nre 's|^\s*https://(.+)|https://wbadmin:wbadmin@\1|ip'
...
SRC_REPO=
```

**Comment by Enteee** [comment]
Hmm this is there by design (see the commend above this function). Sending access tokens over http is a really bad idea and you should probably talk to the person maintaining those repositories.

I am considerung adding a `ALLOW_INSECURE_HTTP_TOKEN` environment variable which allows this, but I am not a huge fan of implementing known insecure functionality. Have to think about this, give me a night or two.

**Comment by KMax** [comment]
It's definitely an insecure option, but I have to use it at least for debugging purposes. In production, it's going to be HTTPS.

**Comment by Enteee** [comment]
ok I'll draft an implementation later today.

**Comment by Enteee** [comment]
see #2, for this.

**Comment by Enteee** [comment]
@KMax , can you please test the change and tell me if this worked for you.

**Comment by KMax** [comment]
@Enteee Yes, it worked.
